default: &default
  adapter: postgresql
  encoding: unicode
  username: weedmaps
  password: weed4everyone
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  url: <%= ENV['DATABASE_URL'] %>
